services:

  gateway-api:
    build:
      context: ./gateway-api
      dockerfile: Dockerfile
    container_name: gateway-api
    ports:
      - "8080:8080"
    environment:
      - ORDER-API_BASE-URL=http://order-api:8080
    networks:
      - microservices-net
    depends_on:
      - order-api

  order-api:
    build:
      context: ./order-api
      dockerfile: Dockerfile
    container_name: order-api
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
